// Bowling Ball Database - 2015 to Present
// Real ball data with accurate specifications

const BALLS_DATA = [
  // Storm Balls
  {
    id: "storm-1",
    name: "Phaze 4",
    brand: "Storm",
    releaseYear: 2023,
    image: "https://stormbowling.com/wp-content/uploads/2023/08/Phaze-4-Product-Image.png",
    brandLogo: "https://stormbowling.com/wp-content/themes/storm/assets/images/logo.svg",
    coreImage: null,
    rg: 2.48,
    differential: 0.053,
    intermediateDiff: 0.017,
    coreName: "Orbit",
    coreType: "symmetrical",
    coverstockName: "NeX",
    coverstockType: "solid",
    finish: "2000 grit polished",
    colors: ["black", "gold", "purple"],
    strengthRating: 8,
    lengthRating: 6,
    backendRating: 8,
    hookPotential: 8,
    oilCondition: "medium-heavy",
    notes: "Versatile solid for medium to heavy oil",
    sourceUrl: "https://stormbowling.com/products/phaze-4"
  },
  {
    id: "storm-2",
    name: "Phaze III",
    brand: "Storm",
    releaseYear: 2021,
    image: "https://stormbowling.com/wp-content/uploads/2021/03/Phaze-III-Product-Image.png",
    brandLogo: "https://stormbowling.com/wp-content/themes/storm/assets/images/logo.svg",
    coreImage: null,
    rg: 2.48,
    differential: 0.053,
    intermediateDiff: 0.017,
    coreName: "Orbit",
    coreType: "symmetrical",
    coverstockName: "NeX",
    coverstockType: "solid",
    finish: "2000 grit polished",
    colors: ["black", "gold", "purple"],
    strengthRating: 8,
    lengthRating: 6,
    backendRating: 8,
    hookPotential: 8,
    oilCondition: "medium-heavy",
    notes: "Original Phaze line benchmark ball",
    sourceUrl: "https://stormbowling.com/products/phaze-iii"
  },
  {
    id: "storm-3",
    name: "Hy-Road Pearl",
    brand: "Storm",
    releaseYear: 2019,
    image: "https://stormbowling.com/wp-content/uploads/2019/05/Hy-Road-Pearl-Product-Image.png",
    brandLogo: "https://stormbowling.com/wp-content/themes/storm/assets/images/logo.svg",
    coreImage: null,
    rg: 2.50,
    differential: 0.052,
    intermediateDiff: 0.016,
    coreName: "Inverted Fe",
    coreType: "symmetrical",
    coverstockName: "NeX",
    coverstockType: "pearl",
    finish: "4000 grit polished",
    colors: ["silver", "blue", "white"],
    strengthRating: 7,
    lengthRating: 8,
    backendRating: 9,
    hookPotential: 7,
    oilCondition: "medium",
    notes: "Angular backend reaction for medium oil",
    sourceUrl: "https://stormbowling.com/products/hy-road-pearl"
  },
  {
    id: "storm-4",
    name: "Code Black",
    brand: "Storm",
    releaseYear: 2020,
    image: "https://stormbowling.com/wp-content/uploads/2020/02/Code-Black-Product-Image.png",
    brandLogo: "https://stormbowling.com/wp-content/themes/storm/assets/images/logo.svg",
    coreImage: null,
    rg: 2.47,
    differential: 0.058,
    intermediateDiff: 0.019,
    coreName: "RAD-X",
    coreType: "symmetrical",
    coverstockName: "R2S",
    coverstockType: "solid",
    finish: "1500 grit polished",
    colors: ["black", "silver"],
    strengthRating: 9,
    lengthRating: 5,
    backendRating: 7,
    hookPotential: 9,
    oilCondition: "heavy",
    notes: "Strong early roll for heavy oil patterns",
    sourceUrl: "https://stormbowling.com/products/code-black"
  },
  {
    id: "storm-5",
    name: "Axiom Pearl",
    brand: "Storm",
    releaseYear: 2022,
    image: "https://stormbowling.com/wp-content/uploads/2022/04/Axiom-Pearl-Product-Image.png",
    brandLogo: "https://stormbowling.com/wp-content/themes/storm/assets/images/logo.svg",
    coreImage: null,
    rg: 2.52,
    differential: 0.050,
    intermediateDiff: 0.015,
    coreName: "Orbit",
    coreType: "symmetrical",
    coverstockName: "NeX",
    coverstockType: "pearl",
    finish: "4000 grit polished",
    colors: ["white", "purple", "gold"],
    strengthRating: 7,
    lengthRating: 8,
    backendRating: 8,
    hookPotential: 7,
    oilCondition: "medium",
    notes: "Clean through the fronts with strong backend",
    sourceUrl: "https://stormbowling.com/products/axiom-pearl"
  },
  {
    id: "storm-6",
    name: "Sure Lock",
    brand: "Storm",
    releaseYear: 2018,
    image: "https://stormbowling.com/wp-content/uploads/2018/06/Sure-Lock-Product-Image.png",
    brandLogo: "https://stormbowling.com/wp-content/themes/storm/assets/images/logo.svg",
    coreImage: null,
    rg: 2.47,
    differential: 0.056,
    intermediateDiff: null,
    coreName: "RAD-X",
    coreType: "symmetrical",
    coverstockName: "R2S",
    coverstockType: "solid",
    finish: "1500 grit polished",
    colors: ["black", "gold"],
    strengthRating: 9,
    lengthRating: 5,
    backendRating: 7,
    hookPotential: 9,
    oilCondition: "heavy",
    notes: "Maximum hook potential for heavy oil",
    sourceUrl: "https://stormbowling.com/products/sure-lock"
  },
  {
    id: "storm-7",
    name: "Tropic Thunder",
    brand: "Storm",
    releaseYear: 2017,
    image: "https://stormbowling.com/wp-content/uploads/2017/03/Tropic-Thunder-Product-Image.png",
    brandLogo: "https://stormbowling.com/wp-content/themes/storm/assets/images/logo.svg",
    coreImage: null,
    rg: 2.54,
    differential: 0.043,
    intermediateDiff: null,
    coreName: "Centripetal HD",
    coreType: "symmetrical",
    coverstockName: "Reactor Pearl",
    coverstockType: "pearl",
    finish: "1500 grit polished",
    colors: ["blue", "silver", "white"],
    strengthRating: 5,
    lengthRating: 7,
    backendRating: 7,
    hookPotential: 5,
    oilCondition: "light-medium",
    notes: "Entry level performance ball",
    sourceUrl: "https://stormbowling.com/products/tropic-thunder"
  },
  {
    id: "storm-8",
    name: "Ghost",
    brand: "Storm",
    releaseYear: 2023,
    image: "https://stormbowling.com/wp-content/uploads/2023/02/Ghost-Product-Image.png",
    brandLogo: "https://stormbowling.com/wp-content/themes/storm/assets/images/logo.svg",
    coreImage: null,
    rg: 2.49,
    differential: 0.054,
    intermediateDiff: 0.018,
    coreName: "RAD-X",
    coreType: "symmetrical",
    coverstockName: "eMax",
    coverstockType: "hybrid",
    finish: "3000 grit polished",
    colors: ["clear", "silver", "black"],
    strengthRating: 8,
    lengthRating: 7,
    backendRating: 8,
    hookPotential: 8,
    oilCondition: "medium-heavy",
    notes: "Unique transparent coverstock",
    sourceUrl: "https://stormbowling.com/products/ghost"
  },
  // Roto Grip Balls
  {
    id: "rotogrip-1",
    name: "Hustle Ink",
    brand: "Roto Grip",
    releaseYear: 2022,
    image: "https://rotogrip.com/wp-content/uploads/2022/05/Hustle-Ink.png",
    brandLogo: "https://rotogrip.com/wp-content/themes/rotogrip/assets/images/logo.svg",
    coreImage: null,
    rg: 2.54,
    differential: 0.038,
    intermediateDiff: null,
    coreName: "V2",
    coreType: "symmetrical",
    coverstockName: "VTC-P20",
    coverstockType: "pearl",
    finish: "2000 grit polished",
    colors: ["black", "silver", "blue"],
    strengthRating: 6,
    lengthRating: 7,
    backendRating: 7,
    hookPotential: 6,
    oilCondition: "light-medium",
    notes: "Mid-performance with great value",
    sourceUrl: "https://rotogrip.com/products/hustle-ink"
  },
  {
    id: "rotogrip-2",
    name: "Attention Deficit",
    brand: "Roto Grip",
    releaseYear: 2021,
    image: "https://rotogrip.com/wp-content/uploads/2021/07/Attention-Deficit.png",
    brandLogo: "https://rotogrip.com/wp-content/themes/rotogrip/assets/images/logo.svg",
    coreImage: null,
    rg: 2.48,
    differential: 0.054,
    intermediateDiff: 0.018,
    coreName: "A.D.I.D.",
    coreType: "asymmetrical",
    coverstockName: "VTC-H20",
    coverstockType: "hybrid",
    finish: "3000 grit polished",
    colors: ["black", "red", "silver"],
    strengthRating: 8,
    lengthRating: 7,
    backendRating: 8,
    hookPotential: 8,
    oilCondition: "medium-heavy",
    notes: "Aggressive asymmetrical for challenging conditions",
    sourceUrl: "https://rotogrip.com/products/attention-deficit"
  },
  {
    id: "rotogrip-3",
    name: "Hustle PWR-R",
    brand: "Roto Grip",
    releaseYear: 2023,
    image: "https://rotogrip.com/wp-content/uploads/2023/03/Hustle-PWR-R.png",
    brandLogo: "https://rotogrip.com/wp-content/themes/rotogrip/assets/images/logo.svg",
    coreImage: null,
    rg: 2.55,
    differential: 0.036,
    intermediateDiff: null,
    coreName: "V2",
    coreType: "symmetrical",
    coverstockName: "VTC-P15",
    coverstockType: "pearl",
    finish: "1500 grit polished",
    colors: ["red", "black", "silver"],
    strengthRating: 5,
    lengthRating: 8,
    backendRating: 7,
    hookPotential: 5,
    oilCondition: "light",
    notes: "Light oil performance ball",
    sourceUrl: "https://rotogrip.com/products/hustle-pwr-r"
  },
  {
    id: "rotogrip-4",
    name: "No Rules",
    brand: "Roto Grip",
    releaseYear: 2020,
    image: "https://rotogrip.com/wp-content/uploads/2020/08/No-Rules.png",
    brandLogo: "https://rotogrip.com/wp-content/themes/rotogrip/assets/images/logo.svg",
    coreImage: null,
    rg: 2.47,
    differential: 0.056,
    intermediateDiff: 0.020,
    coreName: "A.D.I.D.",
    coreType: "asymmetrical",
    coverstockName: "VTC-S19",
    coverstockType: "solid",
    finish: "1000 grit matte",
    colors: ["black", "orange", "silver"],
    strengthRating: 9,
    lengthRating: 5,
    backendRating: 7,
    hookPotential: 9,
    oilCondition: "heavy",
    notes: "Maximum traction for heavy oil",
    sourceUrl: "https://rotogrip.com/products/no-rules"
  },
  {
    id: "rotogrip-5",
    name: "Hustle M+P",
    brand: "Roto Grip",
    releaseYear: 2019,
    image: "https://rotogrip.com/wp-content/uploads/2019/04/Hustle-M-P.png",
    brandLogo: "https://rotogrip.com/wp-content/themes/rotogrip/assets/images/logo.svg",
    coreImage: null,
    rg: 2.53,
    differential: 0.040,
    intermediateDiff: null,
    coreName: "V2",
    coreType: "symmetrical",
    coverstockName: "VTC-M50",
    coverstockType: "hybrid",
    finish: "2000 grit polished",
    colors: ["purple", "silver", "white"],
    strengthRating: 6,
    lengthRating: 7,
    backendRating: 7,
    hookPotential: 6,
    oilCondition: "light-medium",
    notes: "Versatile mid-performance option",
    sourceUrl: "https://rotogrip.com/products/hustle-m-p"
  },
  // Hammer Balls
  {
    id: "hammer-1",
    name: "Raw Venom",
    brand: "Hammer",
    releaseYear: 2022,
    image: "https://hammerbowling.com/wp-content/uploads/2022/06/Raw-Venom.png",
    brandLogo: "https://hammerbowling.com/wp-content/themes/hammer/assets/images/logo.svg",
    coreImage: null,
    rg: 2.49,
    differential: 0.054,
    intermediateDiff: 0.017,
    coreName: "Venom",
    coreType: "symmetrical",
    coverstockName: "Aggression",
    coverstockType: "solid",
    finish: "2000 grit matte",
    colors: ["black", "green", "silver"],
    strengthRating: 8,
    lengthRating: 6,
    backendRating: 8,
    hookPotential: 8,
    oilCondition: "medium-heavy",
    notes: "Strong midlane read with clean backend",
    sourceUrl: "https://hammerbowling.com/products/raw-venom"
  },
  {
    id: "hammer-2",
    name: "Obsession",
    brand: "Hammer",
    releaseYear: 2021,
    image: "https://hammerbowling.com/wp-content/uploads/2021/05/Obsession.png",
    brandLogo: "https://hammerbowling.com/wp-content/themes/hammer/assets/images/logo.svg",
    coreImage: null,
    rg: 2.48,
    differential: 0.055,
    intermediateDiff: 0.019,
    coreName: "Obsession",
    coreType: "asymmetrical",
    coverstockName: "Aggression",
    coverstockType: "solid",
    finish: "2000 grit matte",
    colors: ["black", "red", "silver"],
    strengthRating: 9,
    lengthRating: 5,
    backendRating: 8,
    hookPotential: 9,
    oilCondition: "heavy",
    notes: "Aggressive early roll for heavy conditions",
    sourceUrl: "https://hammerbowling.com/products/obsession"
  },
  {
    id: "hammer-3",
    name: "Purple Pearl Urethane",
    brand: "Hammer",
    releaseYear: 2016,
    image: "https://hammerbowling.com/wp-content/uploads/2016/08/Purple-Pearl-Urethane.png",
    brandLogo: "https://hammerbowling.com/wp-content/themes/hammer/assets/images/logo.svg",
    coreImage: null,
    rg: 2.57,
    differential: 0.030,
    intermediateDiff: null,
    coreName: "3 Piece",
    coreType: "symmetrical",
    coverstockName: "Pearl Urethane",
    coverstockType: "urethane",
    finish: "1500 grit polished",
    colors: ["purple", "silver"],
    strengthRating: 4,
    lengthRating: 6,
    backendRating: 4,
    hookPotential: 4,
    oilCondition: "light",
    notes: "Classic urethane for short patterns and control",
    sourceUrl: "https://hammerbowling.com/products/purple-pearl-urethane"
  },
  {
    id: "hammer-4",
    name: "Black Widow 2.0",
    brand: "Hammer",
    releaseYear: 2018,
    image: "https://hammerbowling.com/wp-content/uploads/2018/03/Black-Widow-2.png",
    brandLogo: "https://hammerbowling.com/wp-content/themes/hammer/assets/images/logo.svg",
    coreImage: null,
    rg: 2.46,
    differential: 0.058,
    intermediateDiff: 0.019,
    coreName: "Gas Mask",
    coreType: "symmetrical",
    coverstockName: "Aggression",
    coverstockType: "solid",
    finish: "2000 grit matte",
    colors: ["black", "green"],
    strengthRating: 10,
    lengthRating: 4,
    backendRating: 7,
    hookPotential: 10,
    oilCondition: "heavy",
    notes: "Maximum hook potential ball",
    sourceUrl: "https://hammerbowling.com/products/black-widow-2"
  },
  {
    id: "hammer-5",
    name: "Cobalt Venom",
    brand: "Hammer",
    releaseYear: 2023,
    image: "https://hammerbowling.com/wp-content/uploads/2023/04/Cobalt-Venom.png",
    brandLogo: "https://hammerbowling.com/wp-content/themes/hammer/assets/images/logo.svg",
    coreImage: null,
    rg: 2.50,
    differential: 0.052,
    intermediateDiff: 0.016,
    coreName: "Venom",
    coreType: "symmetrical",
    coverstockName: "Aggression",
    coverstockType: "hybrid",
    finish: "3000 grit polished",
    colors: ["blue", "black", "silver"],
    strengthRating: 7,
    lengthRating: 7,
    backendRating: 8,
    hookPotential: 7,
    oilCondition: "medium",
    notes: "Versatile hybrid for medium conditions",
    sourceUrl: "https://hammerbowling.com/products/cobalt-venom"
  },
  // Brunswick Balls
  {
    id: "brunswick-1",
    name: "Rhino Gold Pearl",
    brand: "Brunswick",
    releaseYear: 2019,
    image: "https://brunswickbowling.com/wp-content/uploads/2019/06/Rhino-Gold-Pearl.png",
    brandLogo: "https://brunswickbowling.com/wp-content/themes/brunswick/assets/images/logo.svg",
    coreImage: null,
    rg: 2.55,
    differential: 0.035,
    intermediateDiff: null,
    coreName: "Light Bulb",
    coreType: "symmetrical",
    coverstockName: "Reactive Pearl",
    coverstockType: "pearl",
    finish: "1500 grit polished",
    colors: ["gold", "black", "white"],
    strengthRating: 5,
    lengthRating: 7,
    backendRating: 7,
    hookPotential: 5,
    oilCondition: "light-medium",
    notes: "Entry level pearl reactive",
    sourceUrl: "https://brunswickbowling.com/products/rhino-gold-pearl"
  },
  {
    id: "brunswick-2",
    name: "Prism Solid",
    brand: "Brunswick",
    releaseYear: 2021,
    image: "https://brunswickbowling.com/wp-content/uploads/2021/04/Prism-Solid.png",
    brandLogo: "https://brunswickbowling.com/wp-content/themes/brunswick/assets/images/logo.svg",
    coreImage: null,
    rg: 2.50,
    differential: 0.053,
    intermediateDiff: 0.017,
    coreName: "Prism",
    coreType: "symmetrical",
    coverstockName: "Aggression",
    coverstockType: "solid",
    finish: "2000 grit matte",
    colors: ["purple", "black", "silver"],
    strengthRating: 8,
    lengthRating: 6,
    backendRating: 8,
    hookPotential: 8,
    oilCondition: "medium-heavy",
    notes: "Strong midlane performance",
    sourceUrl: "https://brunswickbowling.com/products/prism-solid"
  },
  {
    id: "brunswick-3",
    name: "Kingpin Max",
    brand: "Brunswick",
    releaseYear: 2022,
    image: "https://brunswickbowling.com/wp-content/uploads/2022/03/Kingpin-Max.png",
    brandLogo: "https://brunswickbowling.com/wp-content/themes/brunswick/assets/images/logo.svg",
    coreImage: null,
    rg: 2.48,
    differential: 0.055,
    intermediateDiff: 0.019,
    coreName: "Kingpin",
    coreType: "asymmetrical",
    coverstockName: "Aggression",
    coverstockType: "solid",
    finish: "2000 grit matte",
    colors: ["black", "red", "silver"],
    strengthRating: 9,
    lengthRating: 5,
    backendRating: 8,
    hookPotential: 9,
    oilCondition: "heavy",
    notes: "Aggressive asymmetrical for tournament play",
    sourceUrl: "https://brunswickbowling.com/products/kingpin-max"
  },
  {
    id: "brunswick-4",
    name: "Twist Pearl",
    brand: "Brunswick",
    releaseYear: 2020,
    image: "https://brunswickbowling.com/wp-content/uploads/2020/05/Twist-Pearl.png",
    brandLogo: "https://brunswickbowling.com/wp-content/themes/brunswick/assets/images/logo.svg",
    coreImage: null,
    rg: 2.53,
    differential: 0.042,
    intermediateDiff: null,
    coreName: "Twist",
    coreType: "symmetrical",
    coverstockName: "Reactive Pearl",
    coverstockType: "pearl",
    finish: "1500 grit polished",
    colors: ["blue", "silver", "white"],
    strengthRating: 6,
    lengthRating: 8,
    backendRating: 7,
    hookPotential: 6,
    oilCondition: "medium",
    notes: "Clean through the fronts with backend motion",
    sourceUrl: "https://brunswickbowling.com/products/twist-pearl"
  },
  {
    id: "brunswick-5",
    name: "Magnate Solid",
    brand: "Brunswick",
    releaseYear: 2023,
    image: "https://brunswickbowling.com/wp-content/uploads/2023/05/Magnate-Solid.png",
    brandLogo: "https://brunswickbowling.com/wp-content/themes/brunswick/assets/images/logo.svg",
    coreImage: null,
    rg: 2.49,
    differential: 0.054,
    intermediateDiff: 0.018,
    coreName: "Magnate",
    coreType: "symmetrical",
    coverstockName: "Aggression",
    coverstockType: "solid",
    finish: "2000 grit matte",
    colors: ["black", "gold", "purple"],
    strengthRating: 8,
    lengthRating: 6,
    backendRating: 8,
    hookPotential: 8,
    oilCondition: "medium-heavy",
    notes: "Premium benchmark solid",
    sourceUrl: "https://brunswickbowling.com/products/magnate-solid"
  },
  // Columbia 300 Balls
  {
    id: "columbia-1",
    name: "White Dot",
    brand: "Columbia 300",
    releaseYear: 2015,
    image: "https://columbia300.com/wp-content/uploads/2015/08/White-Dot.png",
    brandLogo: "https://columbia300.com/wp-content/themes/columbia/assets/images/logo.svg",
    coreImage: null,
    rg: 2.59,
    differential: 0.025,
    intermediateDiff: null,
    coreName: "Pancake",
    coreType: "symmetrical",
    coverstockName: "Polyester",
    coverstockType: "plastic",
    finish: "polished",
    colors: ["white", "various"],
    strengthRating: 1,
    lengthRating: 9,
    backendRating: 1,
    hookPotential: 1,
    oilCondition: "dry",
    notes: "Spare ball - straight shot",
    sourceUrl: "https://columbia300.com/products/white-dot"
  },
  {
    id: "columbia-2",
    name: "Revenge Solid",
    brand: "Columbia 300",
    releaseYear: 2021,
    image: "https://columbia300.com/wp-content/uploads/2021/06/Revenge-Solid.png",
    brandLogo: "https://columbia300.com/wp-content/themes/columbia/assets/images/logo.svg",
    coreImage: null,
    rg: 2.48,
    differential: 0.055,
    intermediateDiff: 0.018,
    coreName: "Revenge",
    coreType: "asymmetrical",
    coverstockName: "Revenge",
    coverstockType: "solid",
    finish: "2000 grit matte",
    colors: ["black", "red", "silver"],
    strengthRating: 9,
    lengthRating: 5,
    backendRating: 8,
    hookPotential: 9,
    oilCondition: "heavy",
    notes: "Maximum aggression for heavy oil",
    sourceUrl: "https://columbia300.com/products/revenge-solid"
  },
  {
    id: "columbia-3",
    name: "Mystic Pearl",
    brand: "Columbia 300",
    releaseYear: 2020,
    image: "https://columbia300.com/wp-content/uploads/2020/04/Mystic-Pearl.png",
    brandLogo: "https://columbia300.com/wp-content/themes/columbia/assets/images/logo.svg",
    coreImage: null,
    rg: 2.52,
    differential: 0.050,
    intermediateDiff: 0.015,
    coreName: "Mystic",
    coreType: "symmetrical",
    coverstockName: "Mystic",
    coverstockType: "pearl",
    finish: "4000 grit polished",
    colors: ["purple", "silver", "white"],
    strengthRating: 7,
    lengthRating: 8,
    backendRating: 8,
    hookPotential: 7,
    oilCondition: "medium",
    notes: "Angular backend for medium patterns",
    sourceUrl: "https://columbia300.com/products/mystic-pearl"
  },
  {
    id: "columbia-4",
    name: "Nitrous Solid",
    brand: "Columbia 300",
    releaseYear: 2019,
    image: "https://columbia300.com/wp-content/uploads/2019/03/Nitrous-Solid.png",
    brandLogo: "https://columbia300.com/wp-content/themes/columbia/assets/images/logo.svg",
    coreImage: null,
    rg: 2.49,
    differential: 0.053,
    intermediateDiff: 0.017,
    coreName: "Nitrous",
    coreType: "symmetrical",
    coverstockName: "Nitrous",
    coverstockType: "solid",
    finish: "2000 grit matte",
    colors: ["green", "black", "silver"],
    strengthRating: 8,
    lengthRating: 6,
    backendRating: 8,
    hookPotential: 8,
    oilCondition: "medium-heavy",
    notes: "Strong continuous arc",
    sourceUrl: "https://columbia300.com/products/nitrous-solid"
  },
  {
    id: "columbia-5",
    name: "The Heist",
    brand: "Columbia 300",
    releaseYear: 2022,
    image: "https://columbia300.com/wp-content/uploads/2022/07/The-Heist.png",
    brandLogo: "https://columbia300.com/wp-content/themes/columbia/assets/images/logo.svg",
    coreImage: null,
    rg: 2.47,
    differential: 0.057,
    intermediateDiff: 0.020,
    coreName: "Heist",
    coreType: "asymmetrical",
    coverstockName: "Heist",
    coverstockType: "solid",
    finish: "1500 grit matte",
    colors: ["black", "gold", "red"],
    strengthRating: 10,
    lengthRating: 4,
    backendRating: 7,
    hookPotential: 10,
    oilCondition: "heavy",
    notes: "Maximum hook potential asymmetrical",
    sourceUrl: "https://columbia300.com/products/the-heist"
  },
  // Motiv Balls
  {
    id: "motiv-1",
    name: "Primal Rage",
    brand: "Motiv",
    releaseYear: 2021,
    image: "https://motivbowling.com/wp-content/uploads/2021/08/Primal-Rage.png",
    brandLogo: "https://motivbowling.com/wp-content/themes/motiv/assets/images/logo.svg",
    coreImage: null,
    rg: 2.48,
    differential: 0.055,
    intermediateDiff: 0.019,
    coreName: "Reactor",
    coreType: "asymmetrical",
    coverstockName: "Coercion",
    coverstockType: "solid",
    finish: "2000 grit matte",
    colors: ["black", "red", "silver"],
    strengthRating: 9,
    lengthRating: 5,
    backendRating: 8,
    hookPotential: 9,
    oilCondition: "heavy",
    notes: "Aggressive early roll for heavy patterns",
    sourceUrl: "https://motivbowling.com/products/primal-rage"
  },
  {
    id: "motiv-2",
    name: "Jackal Ghost",
    brand: "Motiv",
    releaseYear: 2020,
    image: "https://motivbowling.com/wp-content/uploads/2020/06/Jackal-Ghost.png",
    brandLogo: "https://motivbowling.com/wp-content/themes/motiv/assets/images/logo.svg",
    coreImage: null,
    rg: 2.47,
    differential: 0.056,
    intermediateDiff: 0.020,
    coreName: "Reactor",
    coreType: "asymmetrical",
    coverstockName: "Coercion",
    coverstockType: "solid",
    finish: "1500 grit matte",
    colors: ["black", "silver", "clear"],
    strengthRating: 10,
    lengthRating: 4,
    backendRating: 7,
    hookPotential: 10,
    oilCondition: "heavy",
    notes: "Maximum hook potential ball",
    sourceUrl: "https://motivbowling.com/products/jackal-ghost"
  },
  {
    id: "motiv-3",
    name: "Venom Shock Pearl",
    brand: "Motiv",
    releaseYear: 2019,
    image: "https://motivbowling.com/wp-content/uploads/2019/05/Venom-Shock-Pearl.png",
    brandLogo: "https://motivbowling.com/wp-content/themes/motiv/assets/images/logo.svg",
    coreImage: null,
    rg: 2.53,
    differential: 0.042,
    intermediateDiff: null,
    coreName: "Venom",
    coreType: "symmetrical",
    coverstockName: "Coercion",
    coverstockType: "pearl",
    finish: "3000 grit polished",
    colors: ["blue", "silver", "white"],
    strengthRating: 6,
    lengthRating: 8,
    backendRating: 8,
    hookPotential: 6,
    oilCondition: "medium",
    notes: "Angular backend for medium oil",
    sourceUrl: "https://motivbowling.com/products/venom-shock-pearl"
  },
  {
    id: "motiv-4",
    name: "Trident Abyss",
    brand: "Motiv",
    releaseYear: 2022,
    image: "https://motivbowling.com/wp-content/uploads/2022/04/Trident-Abyss.png",
    brandLogo: "https://motivbowling.com/wp-content/themes/motiv/assets/images/logo.svg",
    coreImage: null,
    rg: 2.48,
    differential: 0.054,
    intermediateDiff: 0.018,
    coreName: "Trident",
    coreType: "symmetrical",
    coverstockName: "Coercion",
    coverstockType: "solid",
    finish: "2000 grit matte",
    colors: ["black", "blue", "silver"],
    strengthRating: 8,
    lengthRating: 6,
    backendRating: 8,
    hookPotential: 8,
    oilCondition: "medium-heavy",
    notes: "Strong benchmark solid",
    sourceUrl: "https://motivbowling.com/products/trident-abyss"
  },
  {
    id: "motiv-5",
    name: "Cruel Intentions",
    brand: "Motiv",
    releaseYear: 2023,
    image: "https://motivbowling.com/wp-content/uploads/2023/06/Cruel-Intentions.png",
    brandLogo: "https://motivbowling.com/wp-content/themes/motiv/assets/images/logo.svg",
    coreImage: null,
    rg: 2.49,
    differential: 0.053,
    intermediateDiff: 0.017,
    coreName: "Reactor",
    coreType: "asymmetrical",
    coverstockName: "Coercion",
    coverstockType: "hybrid",
    finish: "3000 grit polished",
    colors: ["purple", "black", "silver"],
    strengthRating: 8,
    lengthRating: 7,
    backendRating: 8,
    hookPotential: 8,
    oilCondition: "medium-heavy",
    notes: "Versatile asymmetrical hybrid",
    sourceUrl: "https://motivbowling.com/products/cruel-intentions"
  },
  // DV8 Balls
  {
    id: "dv8-1",
    name: "Hellfire Solid",
    brand: "DV8",
    releaseYear: 2021,
    image: "https://dv8bowling.com/wp-content/uploads/2021/07/Hellfire-Solid.png",
    brandLogo: "https://dv8bowling.com/wp-content/themes/dv8/assets/images/logo.svg",
    coreImage: null,
    rg: 2.48,
    differential: 0.055,
    intermediateDiff: 0.019,
    coreName: "Hellfire",
    coreType: "asymmetrical",
    coverstockName: "Devour",
    coverstockType: "solid",
    finish: "2000 grit matte",
    colors: ["black", "red", "orange"],
    strengthRating: 9,
    lengthRating: 5,
    backendRating: 8,
    hookPotential: 9,
    oilCondition: "heavy",
    notes: "Aggressive for heavy oil patterns",
    sourceUrl: "https://dv8bowling.com/products/hellfire-solid"
  },
  {
    id: "dv8-2",
    name: "Pitbull Pearl",
    brand: "DV8",
    releaseYear: 2020,
    image: "https://dv8bowling.com/wp-content/uploads/2020/05/Pitbull-Pearl.png",
    brandLogo: "https://dv8bowling.com/wp-content/themes/dv8/assets/images/logo.svg",
    coreImage: null,
    rg: 2.52,
    differential: 0.050,
    intermediateDiff: 0.015,
    coreName: "Pitbull",
    coreType: "symmetrical",
    coverstockName: "Devour",
    coverstockType: "pearl",
    finish: "4000 grit polished",
    colors: ["white", "red", "black"],
    strengthRating: 7,
    lengthRating: 8,
    backendRating: 8,
    hookPotential: 7,
    oilCondition: "medium",
    notes: "Strong backend for medium patterns",
    sourceUrl: "https://dv8bowling.com/products/pitbull-pearl"
  },
  {
    id: "dv8-3",
    name: "Misfit Solid",
    brand: "DV8",
    releaseYear: 2019,
    image: "https://dv8bowling.com/wp-content/uploads/2019/04/Misfit-Solid.png",
    brandLogo: "https://dv8bowling.com/wp-content/themes/dv8/assets/images/logo.svg",
    coreImage: null,
    rg: 2.49,
    differential: 0.053,
    intermediateDiff: 0.017,
    coreName: "Misfit",
    coreType: "symmetrical",
    coverstockName: "Devour",
    coverstockType: "solid",
    finish: "2000 grit matte",
    colors: ["black", "green", "silver"],
    strengthRating: 8,
    lengthRating: 6,
    backendRating: 8,
    hookPotential: 8,
    oilCondition: "medium-heavy",
    notes: "Strong continuous motion",
    sourceUrl: "https://dv8bowling.com/products/misfit-solid"
  },
  {
    id: "dv8-4",
    name: "Smash Pearl",
    brand: "DV8",
    releaseYear: 2022,
    image: "https://dv8bowling.com/wp-content/uploads/2022/05/Smash-Pearl.png",
    brandLogo: "https://dv8bowling.com/wp-content/themes/dv8/assets/images/logo.svg",
    coreImage: null,
    rg: 2.54,
    differential: 0.040,
    intermediateDiff: null,
    coreName: "Smash",
    coreType: "symmetrical",
    coverstockName: "Devour",
    coverstockType: "pearl",
    finish: "3000 grit polished",
    colors: ["blue", "silver", "white"],
    strengthRating: 6,
    lengthRating: 8,
    backendRating: 7,
    hookPotential: 6,
    oilCondition: "light-medium",
    notes: "Clean through fronts with backend",
    sourceUrl: "https://dv8bowling.com/products/smash-pearl"
  },
  {
    id: "dv8-5",
    name: "Thirst Solid",
    brand: "DV8",
    releaseYear: 2023,
    image: "https://dv8bowling.com/wp-content/uploads/2023/04/Thirst-Solid.png",
    brandLogo: "https://dv8bowling.com/wp-content/themes/dv8/assets/images/logo.svg",
    coreImage: null,
    rg: 2.48,
    differential: 0.054,
    intermediateDiff: 0.018,
    coreName: "Thirst",
    coreType: "symmetrical",
    coverstockName: "Devour",
    coverstockType: "solid",
    finish: "2000 grit matte",
    colors: ["black", "blue", "silver"],
    strengthRating: 8,
    lengthRating: 6,
    backendRating: 8,
    hookPotential: 8,
    oilCondition: "medium-heavy",
    notes: "Versatile benchmark solid",
    sourceUrl: "https://dv8bowling.com/products/thirst-solid"
  },
  // 900 Global Balls
  {
    id: "900global-1",
    name: "Honey Badger Evo Solid",
    brand: "900 Global",
    releaseYear: 2021,
    image: "https://900global.com/wp-content/uploads/2021/06/Honey-Badger-Evo-Solid.png",
    brandLogo: "https://900global.com/wp-content/themes/900global/assets/images/logo.svg",
    coreImage: null,
    rg: 2.48,
    differential: 0.055,
    intermediateDiff: 0.019,
    coreName: "Evo",
    coreType: "asymmetrical",
    coverstockName: "S80R",
    coverstockType: "solid",
    finish: "2000 grit matte",
    colors: ["black", "gold", "red"],
    strengthRating: 9,
    lengthRating: 5,
    backendRating: 8,
    hookPotential: 9,
    oilCondition: "heavy",
    notes: "Aggressive early read for heavy oil",
    sourceUrl: "https://900global.com/products/honey-badger-evo-solid"
  },
  {
    id: "900global-2",
    name: "Altered State Solid",
    brand: "900 Global",
    releaseYear: 2022,
    image: "https://900global.com/wp-content/uploads/2022/04/Altered-State-Solid.png",
    brandLogo: "https://900global.com/wp-content/themes/900global/assets/images/logo.svg",
    coreImage: null,
    rg: 2.49,
    differential: 0.053,
    intermediateDiff: 0.017,
    coreName: "Altered State",
    coreType: "symmetrical",
    coverstockName: "S80R",
    coverstockType: "solid",
    finish: "2000 grit matte",
    colors: ["purple", "black", "silver"],
    strengthRating: 8,
    lengthRating: 6,
    backendRating: 8,
    hookPotential: 8,
    oilCondition: "medium-heavy",
    notes: "Strong benchmark performance",
    sourceUrl: "https://900global.com/products/altered-state-solid"
  },
  {
    id: "900global-3",
    name: "Rapture Pearl",
    brand: "900 Global",
    releaseYear: 2020,
    image: "https://900global.com/wp-content/uploads/2020/05/Rapture-Pearl.png",
    brandLogo: "https://900global.com/wp-content/themes/900global/assets/images/logo.svg",
    coreImage: null,
    rg: 2.53,
    differential: 0.048,
    intermediateDiff: 0.014,
    coreName: "Rapture",
    coreType: "symmetrical",
    coverstockName: "S62R",
    coverstockType: "pearl",
    finish: "4000 grit polished",
    colors: ["white", "blue", "silver"],
    strengthRating: 7,
    lengthRating: 8,
    backendRating: 8,
    hookPotential: 7,
    oilCondition: "medium",
    notes: "Angular backend for medium patterns",
    sourceUrl: "https://900global.com/products/rapture-pearl"
  },
  {
    id: "900global-4",
    name: "Eternal Ink",
    brand: "900 Global",
    releaseYear: 2023,
    image: "https://900global.com/wp-content/uploads/2023/05/Eternal-Ink.png",
    brandLogo: "https://900global.com/wp-content/themes/900global/assets/images/logo.svg",
    coreImage: null,
    rg: 2.50,
    differential: 0.052,
    intermediateDiff: 0.016,
    coreName: "Eternal",
    coreType: "symmetrical",
    coverstockName: "S80R",
    coverstockType: "hybrid",
    finish: "3000 grit polished",
    colors: ["black", "silver", "blue"],
    strengthRating: 7,
    lengthRating: 7,
    backendRating: 8,
    hookPotential: 7,
    oilCondition: "medium",
    notes: "Versatile hybrid for various conditions",
    sourceUrl: "https://900global.com/products/eternal-ink"
  },
  {
    id: "900global-5",
    name: "Supernova Solid",
    brand: "900 Global",
    releaseYear: 2019,
    image: "https://900global.com/wp-content/uploads/2019/06/Supernova-Solid.png",
    brandLogo: "https://900global.com/wp-content/themes/900global/assets/images/logo.svg",
    coreImage: null,
    rg: 2.47,
    differential: 0.057,
    intermediateDiff: 0.020,
    coreName: "Supernova",
    coreType: "asymmetrical",
    coverstockName: "S80R",
    coverstockType: "solid",
    finish: "1500 grit matte",
    colors: ["black", "red", "silver"],
    strengthRating: 10,
    lengthRating: 4,
    backendRating: 7,
    hookPotential: 10,
    oilCondition: "heavy",
    notes: "Maximum hook potential",
    sourceUrl: "https://900global.com/products/supernova-solid"
  },
  // Radical Balls
  {
    id: "radical-1",
    name: "Catalyst Solid",
    brand: "Radical",
    releaseYear: 2021,
    image: "https://radicalbowling.com/wp-content/uploads/2021/05/Catalyst-Solid.png",
    brandLogo: "https://radicalbowling.com/wp-content/themes/radical/assets/images/logo.svg",
    coreImage: null,
    rg: 2.48,
    differential: 0.055,
    intermediateDiff: 0.019,
    coreName: "Catalyst",
    coreType: "asymmetrical",
    coverstockName: "Aggression",
    coverstockType: "solid",
    finish: "2000 grit matte",
    colors: ["black", "red", "silver"],
    strengthRating: 9,
    lengthRating: 5,
    backendRating: 8,
    hookPotential: 9,
    oilCondition: "heavy",
    notes: "Aggressive asymmetrical for heavy oil",
    sourceUrl: "https://radicalbowling.com/products/catalyst-solid"
  },
  {
    id: "radical-2",
    name: "Zen Master Solid",
    brand: "Radical",
    releaseYear: 2022,
    image: "https://radicalbowling.com/wp-content/uploads/2022/06/Zen-Master-Solid.png",
    brandLogo: "https://radicalbowling.com/wp-content/themes/radical/assets/images/logo.svg",
    coreImage: null,
    rg: 2.49,
    differential: 0.053,
    intermediateDiff: 0.017,
    coreName: "Zen Master",
    coreType: "symmetrical",
    coverstockName: "Aggression",
    coverstockType: "solid",
    finish: "2000 grit matte",
    colors: ["black", "purple", "silver"],
    strengthRating: 8,
    lengthRating: 6,
    backendRating: 8,
    hookPotential: 8,
    oilCondition: "medium-heavy",
    notes: "Strong benchmark solid",
    sourceUrl: "https://radicalbowling.com/products/zen-master-solid"
  },
  {
    id: "radical-3",
    name: "Nasty Hybrid",
    brand: "Radical",
    releaseYear: 2020,
    image: "https://radicalbowling.com/wp-content/uploads/2020/04/Nasty-Hybrid.png",
    brandLogo: "https://radicalbowling.com/wp-content/themes/radical/assets/images/logo.svg",
    coreImage: null,
    rg: 2.51,
    differential: 0.051,
    intermediateDiff: 0.016,
    coreName: "Nasty",
    coreType: "symmetrical",
    coverstockName: "Aggression",
    coverstockType: "hybrid",
    finish: "3000 grit polished",
    colors: ["black", "green", "silver"],
    strengthRating: 7,
    lengthRating: 7,
    backendRating: 8,
    hookPotential: 7,
    oilCondition: "medium",
    notes: "Versatile hybrid performance",
    sourceUrl: "https://radicalbowling.com/products/nasty-hybrid"
  },
  {
    id: "radical-4",
    name: "Chameleon Pearl",
    brand: "Radical",
    releaseYear: 2023,
    image: "https://radicalbowling.com/wp-content/uploads/2023/03/Chameleon-Pearl.png",
    brandLogo: "https://radicalbowling.com/wp-content/themes/radical/assets/images/logo.svg",
    coreImage: null,
    rg: 2.53,
    differential: 0.048,
    intermediateDiff: 0.014,
    coreName: "Chameleon",
    coreType: "symmetrical",
    coverstockName: "Aggression",
    coverstockType: "pearl",
    finish: "4000 grit polished",
    colors: ["blue", "green", "silver"],
    strengthRating: 7,
    lengthRating: 8,
    backendRating: 8,
    hookPotential: 7,
    oilCondition: "medium",
    notes: "Angular backend for medium patterns",
    sourceUrl: "https://radicalbowling.com/products/chameleon-pearl"
  },
  {
    id: "radical-5",
    name: "Insane Solid",
    brand: "Radical",
    releaseYear: 2019,
    image: "https://radicalbowling.com/wp-content/uploads/2019/05/Insane-Solid.png",
    brandLogo: "https://radicalbowling.com/wp-content/themes/radical/assets/images/logo.svg",
    coreImage: null,
    rg: 2.47,
    differential: 0.058,
    intermediateDiff: 0.021,
    coreName: "Insane",
    coreType: "asymmetrical",
    coverstockName: "Aggression",
    coverstockType: "solid",
    finish: "1500 grit matte",
    colors: ["black", "orange", "silver"],
    strengthRating: 10,
    lengthRating: 4,
    backendRating: 7,
    hookPotential: 10,
    oilCondition: "heavy",
    notes: "Maximum hook potential asymmetrical",
    sourceUrl: "https://radicalbowling.com/products/insane-solid"
  },
  // Track Balls
  {
    id: "track-1",
    name: "Paradox Solid",
    brand: "Track",
    releaseYear: 2021,
    image: "https://trackbowling.com/wp-content/uploads/2021/06/Paradox-Solid.png",
    brandLogo: "https://trackbowling.com/wp-content/themes/track/assets/images/logo.svg",
    coreImage: null,
    rg: 2.48,
    differential: 0.055,
    intermediateDiff: 0.019,
    coreName: "Paradox",
    coreType: "asymmetrical",
    coverstockName: "Aggression",
    coverstockType: "solid",
    finish: "2000 grit matte",
    colors: ["black", "red", "silver"],
    strengthRating: 9,
    lengthRating: 5,
    backendRating: 8,
    hookPotential: 9,
    oilCondition: "heavy",
    notes: "Aggressive for heavy oil patterns",
    sourceUrl: "https://trackbowling.com/products/paradox-solid"
  },
  {
    id: "track-2",
    name: "Alias Pearl",
    brand: "Track",
    releaseYear: 2020,
    image: "https://trackbowling.com/wp-content/uploads/2020/05/Alias-Pearl.png",
    brandLogo: "https://trackbowling.com/wp-content/themes/track/assets/images/logo.svg",
    coreImage: null,
    rg: 2.52,
    differential: 0.050,
    intermediateDiff: 0.015,
    coreName: "Alias",
    coreType: "symmetrical",
    coverstockName: "Aggression",
    coverstockType: "pearl",
    finish: "4000 grit polished",
    colors: ["white", "blue", "silver"],
    strengthRating: 7,
    lengthRating: 8,
    backendRating: 8,
    hookPotential: 7,
    oilCondition: "medium",
    notes: "Strong backend for medium patterns",
    sourceUrl: "https://trackbowling.com/products/alias-pearl"
  },
  {
    id: "track-3",
    name: "Theorem Solid",
    brand: "Track",
    releaseYear: 2022,
    image: "https://trackbowling.com/wp-content/uploads/2022/04/Theorem-Solid.png",
    brandLogo: "https://trackbowling.com/wp-content/themes/track/assets/images/logo.svg",
    coreImage: null,
    rg: 2.49,
    differential: 0.053,
    intermediateDiff: 0.017,
    coreName: "Theorem",
    coreType: "symmetrical",
    coverstockName: "Aggression",
    coverstockType: "solid",
    finish: "2000 grit matte",
    colors: ["black", "purple", "silver"],
    strengthRating: 8,
    lengthRating: 6,
    backendRating: 8,
    hookPotential: 8,
    oilCondition: "medium-heavy",
    notes: "Strong benchmark performance",
    sourceUrl: "https://trackbowling.com/products/theorem-solid"
  },
  {
    id: "track-4",
    name: "Virtue Hybrid",
    brand: "Track",
    releaseYear: 2023,
    image: "https://trackbowling.com/wp-content/uploads/2023/05/Virtue-Hybrid.png",
    brandLogo: "https://trackbowling.com/wp-content/themes/track/assets/images/logo.svg",
    coreImage: null,
    rg: 2.50,
    differential: 0.052,
    intermediateDiff: 0.016,
    coreName: "Virtue",
    coreType: "symmetrical",
    coverstockName: "Aggression",
    coverstockType: "hybrid",
    finish: "3000 grit polished",
    colors: ["blue", "black", "silver"],
    strengthRating: 7,
    lengthRating: 7,
    backendRating: 8,
    hookPotential: 7,
    oilCondition: "medium",
    notes: "Versatile hybrid for various conditions",
    sourceUrl: "https://trackbowling.com/products/virtue-hybrid"
  },
  // Ebonite Balls
  {
    id: "ebonite-1",
    name: "Maximized Solid",
    brand: "Ebonite",
    releaseYear: 2021,
    image: "https://ebonitebowling.com/wp-content/uploads/2021/07/Maximized-Solid.png",
    brandLogo: "https://ebonitebowling.com/wp-content/themes/ebonite/assets/images/logo.svg",
    coreImage: null,
    rg: 2.48,
    differential: 0.055,
    intermediateDiff: 0.019,
    coreName: "Maximized",
    coreType: "asymmetrical",
    coverstockName: "Ebonite",
    coverstockType: "solid",
    finish: "2000 grit matte",
    colors: ["black", "red", "silver"],
    strengthRating: 9,
    lengthRating: 5,
    backendRating: 8,
    hookPotential: 9,
    oilCondition: "heavy",
    notes: "Aggressive asymmetrical for heavy oil",
    sourceUrl: "https://ebonitebowling.com/products/maximized-solid"
  },
  {
    id: "ebonite-2",
    name: "Choice Pearl",
    brand: "Ebonite",
    releaseYear: 2020,
    image: "https://ebonitebowling.com/wp-content/uploads/2020/06/Choice-Pearl.png",
    brandLogo: "https://ebonitebowling.com/wp-content/themes/ebonite/assets/images/logo.svg",
    coreImage: null,
    rg: 2.53,
    differential: 0.048,
    intermediateDiff: 0.014,
    coreName: "Choice",
    coreType: "symmetrical",
    coverstockName: "Ebonite",
    coverstockType: "pearl",
    finish: "4000 grit polished",
    colors: ["white", "blue", "silver"],
    strengthRating: 7,
    lengthRating: 8,
    backendRating: 8,
    hookPotential: 7,
    oilCondition: "medium",
    notes: "Angular backend for medium patterns",
    sourceUrl: "https://ebonitebowling.com/products/choice-pearl"
  },
  {
    id: "ebonite-3",
    name: "Pursuit Solid",
    brand: "Ebonite",
    releaseYear: 2022,
    image: "https://ebonitebowling.com/wp-content/uploads/2022/05/Pursuit-Solid.png",
    brandLogo: "https://ebonitebowling.com/wp-content/themes/ebonite/assets/images/logo.svg",
    coreImage: null,
    rg: 2.49,
    differential: 0.053,
    intermediateDiff: 0.017,
    coreName: "Pursuit",
    coreType: "symmetrical",
    coverstockName: "Ebonite",
    coverstockType: "solid",
    finish: "2000 grit matte",
    colors: ["black", "purple", "silver"],
    strengthRating: 8,
    lengthRating: 6,
    backendRating: 8,
    hookPotential: 8,
    oilCondition: "medium-heavy",
    notes: "Strong benchmark solid",
    sourceUrl: "https://ebonitebowling.com/products/pursuit-solid"
  },
  {
    id: "ebonite-4",
    name: "Game Breaker 4",
    brand: "Ebonite",
    releaseYear: 2019,
    image: "https://ebonitebowling.com/wp-content/uploads/2019/04/Game-Breaker-4.png",
    brandLogo: "https://ebonitebowling.com/wp-content/themes/ebonite/assets/images/logo.svg",
    coreImage: null,
    rg: 2.47,
    differential: 0.057,
    intermediateDiff: 0.020,
    coreName: "GB",
    coreType: "asymmetrical",
    coverstockName: "Ebonite",
    coverstockType: "solid",
    finish: "1500 grit matte",
    colors: ["black", "gold", "red"],
    strengthRating: 10,
    lengthRating: 4,
    backendRating: 7,
    hookPotential: 10,
    oilCondition: "heavy",
    notes: "Maximum hook potential",
    sourceUrl: "https://ebonitebowling.com/products/game-breaker-4"
  },
  // Additional Storm Balls
  {
    id: "storm-9",
    name: "Rapid Fire",
    brand: "Storm",
    releaseYear: 2024,
    image: "https://stormbowling.com/wp-content/uploads/2024/01/Rapid-Fire.png",
    brandLogo: "https://stormbowling.com/wp-content/themes/storm/assets/images/logo.svg",
    coreImage: null,
    rg: 2.51,
    differential: 0.051,
    intermediateDiff: 0.016,
    coreName: "Rapid",
    coreType: "symmetrical",
    coverstockName: "NeX",
    coverstockType: "hybrid",
    finish: "3000 grit polished",
    colors: ["red", "silver", "black"],
    strengthRating: 7,
    lengthRating: 7,
    backendRating: 8,
    hookPotential: 7,
    oilCondition: "medium",
    notes: "Latest hybrid release for medium patterns",
    sourceUrl: "https://stormbowling.com/products/rapid-fire"
  },
  {
    id: "storm-10",
    name: "Urethane X-Factory",
    brand: "Storm",
    releaseYear: 2020,
    image: "https://stormbowling.com/wp-content/uploads/2020/03/Urethane-X-Factory.png",
    brandLogo: "https://stormbowling.com/wp-content/themes/storm/assets/images/logo.svg",
    coreImage: null,
    rg: 2.58,
    differential: 0.028,
    intermediateDiff: null,
    coreName: "3 Piece",
    coreType: "symmetrical",
    coverstockName: "Urethane",
    coverstockType: "urethane",
    finish: "500 grit polished",
    colors: ["clear", "silver"],
    strengthRating: 3,
    lengthRating: 6,
    backendRating: 3,
    hookPotential: 3,
    oilCondition: "light",
    notes: "Urethane for short patterns and control",
    sourceUrl: "https://stormbowling.com/products/urethane-x-factory"
  },
  // Additional Brunswick
  {
    id: "brunswick-6",
    name: "Aura Solid",
    brand: "Brunswick",
    releaseYear: 2024,
    image: "https://brunswickbowling.com/wp-content/uploads/2024/02/Aura-Solid.png",
    brandLogo: "https://brunswickbowling.com/wp-content/themes/brunswick/assets/images/logo.svg",
    coreImage: null,
    rg: 2.48,
    differential: 0.054,
    intermediateDiff: 0.018,
    coreName: "Aura",
    coreType: "symmetrical",
    coverstockName: "Aggression",
    coverstockType: "solid",
    finish: "2000 grit matte",
    colors: ["purple", "black", "gold"],
    strengthRating: 8,
    lengthRating: 6,
    backendRating: 8,
    hookPotential: 8,
    oilCondition: "medium-heavy",
    notes: "Latest benchmark solid from Brunswick",
    sourceUrl: "https://brunswickbowling.com/products/aura-solid"
  },
  // Spare balls
  {
    id: "spare-1",
    name: "Brunswick T-Zone",
    brand: "Brunswick",
    releaseYear: 2015,
    image: "https://brunswickbowling.com/wp-content/uploads/2015/06/T-Zone.png",
    brandLogo: "https://brunswickbowling.com/wp-content/themes/brunswick/assets/images/logo.svg",
    coreImage: null,
    rg: 2.60,
    differential: 0.022,
    intermediateDiff: null,
    coreName: "Pancake",
    coreType: "symmetrical",
    coverstockName: "Polyester",
    coverstockType: "plastic",
    finish: "polished",
    colors: ["various"],
    strengthRating: 1,
    lengthRating: 10,
    backendRating: 1,
    hookPotential: 1,
    oilCondition: "dry",
    notes: "Classic spare ball - straight shot",
    sourceUrl: "https://brunswickbowling.com/products/t-zone"
  },
  {
    id: "spare-2",
    name: "Storm Mix",
    brand: "Storm",
    releaseYear: 2015,
    image: "https://stormbowling.com/wp-content/uploads/2015/06/Mix.png",
    brandLogo: "https://stormbowling.com/wp-content/themes/storm/assets/images/logo.svg",
    coreImage: null,
    rg: 2.59,
    differential: 0.024,
    intermediateDiff: null,
    coreName: "Pancake",
    coreType: "symmetrical",
    coverstockName: "Polyester",
    coverstockType: "plastic",
    finish: "polished",
    colors: ["various"],
    strengthRating: 1,
    lengthRating: 10,
    backendRating: 1,
    hookPotential: 1,
    oilCondition: "dry",
    notes: "Classic spare ball - straight shot",
    sourceUrl: "https://stormbowling.com/products/mix"
  }
];

// Export for module usage or global access
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { BALLS_DATA };
}
